# Generated by Django 4.2 on 2023-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_coordinates',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
