# Generated by Django 4.2 on 2023-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_ingradient_name_alter_meal_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingradient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
