# Generated by Django 4.2 on 2023-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_ingradient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
