# Generated by Django 4.2 on 2023-05-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ingradient',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='ingradients',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
    ]
