# Generated by Django 4.2 on 2023-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_restaurant_types_rename_ingradient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/images/'),
        ),
    ]
