# Generated by Django 4.2 on 2023-05-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_meal_price_restaurant_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant_Types',
            new_name='Restaurant_Type',
        ),
    ]
