# Generated by Django 4.2 on 2023-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0011_rename_restaurant_types_restaurant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(blank=True, to='deliveries.meal_type'),
        ),
    ]
