# Generated by Django 4.2 on 2023-05-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0012_meal_type_meal_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='deliveries.restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='deliveries.restaurant'),
        ),
    ]
