# Generated by Django 4.2 on 2023-05-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0014_alter_meal_price_alter_restaurant_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_stamp_time', models.DateTimeField(auto_now_add=True)),
                ('meals', models.ManyToManyField(to='deliveries.meal')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='deliveries.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
