# Generated by Django 4.2 on 2023-05-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0015_order_delete_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='meal_price',
            field=models.FloatField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax_price',
            field=models.FloatField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
