# Generated by Django 4.2 on 2023-05-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0016_order_delivery_price_order_full_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='meal_price',
            new_name='subtotal',
        ),
    ]
